#!/bin/bash
# zmogrify - Run dracut and configure grub to boot with root on zfs.

kver=$1

[[ -z "${kver}" ]] && kver=$(uname -r)

/usr/bin/dracut -fv --kver $kver
md5sum /boot/initramfs-${kver}.img > /boot/initramfs-4.13.9-200.fc26.x86_64.md5sum
if [[ -z "$(mount|grep /boot/efi)" ]];then
  mount /boot/efi
  mounted='yes'
fi

grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
grubby --set-default-index 0
mkdir -p /boot/efi/EFI/fedora/x86_64-efi
cp -a /usr/lib/grub/x86_64-efi/zfs.mod /boot/efi/EFI/fedora/x86_64-efi

if [[ "x${mounted}" == "xyes" ]];then
  umount /boot/efi
fi

